[[s2i-aspnet-example]]
= .NET Core Sample App for OpenShift

This repository contains an example project that can be built using the
https://github.com/redhat-developer/s2i-dotnetcore[s2i-dotnetcore] builder
image, which can be used to create reproducible Docker images from your .NET
Core project's source code. The resulting images can be run using
https://docker.com[Docker] or deployed to OpenShift.

For more information about using these images with OpenShift, please see
the official
https://docs.openshift.com/enterprise/latest/using_images/s2i_images/dot_net_core.html[OpenShift
Documentation].

= Run Natively (Mac, Linux, Win)

First instal C# dotnet core SDK from https://www.microsoft.com/net/download/core 

[source]
----
git clone https://github.com/DFEAGILEDEVOPS/SimplePaaSSprint0.git 
cd SimplePaaSSprint0/app
dotnet run
----

It should start a webserver running at http://localhost:5000

= Building and Running with s2i (source-to-image)

The sample application can be built and run either within OpenShift or
standalone by combining the application using s2i tool and running with
existing image using Docker. The following sections describes these processes.

== OpenShift

The dotnet-example template at https://github.com/redhat-developer/s2i-dotnetcore instantiates the example application.
The https://github.com/redhat-developer/s2i-dotnetcore/blob/master/README.md[README.md] describes how to use the template.

# Standalone

To build a new .NET Core application using a previously existing s2i-dotnetcore
builder, `dotnet/dotnet-20-rhel7`, execute the following command:

[source]
----
docker pull registry.access.redhat.com/dotnet/dotnet-20-rhel7
s2i build --ref=dotnetcore-2.0 --context-dir=app https://github.com/DFEAGILEDEVOPS/SimplePaaSSprint0.git registry.access.redhat.com/dotnet/dotnet-20-rhel7:latest sprint0
----

The resulting image can be executed locally using docker (try "Docker for Mac" or "Docker for Windows"):

[source]
----
docker run -d -p 8080:8080 sprint0
----

Once the container is running, it should be accessible using your browser at http://127.0.0.1:8080

[[copyright-license]]
Copyright and License
~~~~~~~~~~~~~~~~~~~~~

Portions Copyright 2016-2017 by Red Hat, Inc. Licensed under the Apache License, Version 2.0 (the "License"); you may not
use this package except in compliance with the License (see the `LICENSE` file
included in this distribution). You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
License for the specific language governing permissions and limitations under
the License.
